#-------------------------------
# General Site Settings

title: Courage 커리지 | 잡다한 개발 블로그 Developer Blog
logo: logo.png # You can add own logo
description: Courage 의 잡다한 개발 블로그입니다. # Add your awesome description
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://courage-max.github.io" # The base hostname & protocol for your site, e.g. http://example.com

# Preloader
preloader: true # To disable preloader change value to false

menu:
  - url: /
    name: Home
  - url: /about/
    name: About
  - url: /categories/
    name: Categories
  - url: /contact/
    name: Contact

# *** NOTE ***
# You can add submenus. For example:

#  menu:
#  - url: /
#    name: Home
#  - url: /travel/
#    name: Travel
#     submenu:
#      - url: /peru/
#        name: Peru
# ----------------------------------

layout_home_page: true # Homepage layout ( two layout is available, you can set the another layout by change the value of layout_home_page "true" to "false")

featured-post-slider: true # You can enable or disable the featured-post-slider using true or false values.

#-------------------------------
# Hero Section
hero:
  hero-subtitle: 개발자 커리지의 블로그입니다!
  hero-banner: iamcourage.png # Add your banner image '/assets/images/'

#-------------------------------
# Author Settings
author:
  name: Courage

#-------------------------------
# Contact Info
#contact:
  email: seoyeong7.choi@gmail.com
# phone: +90 000 333 22
# address:
#   city: Sydney
#   street: 6 rip carl Avenue CA 90733

# Contact Form
contact-form: seoyeong7.choi@gmail.com

# Social links
social:
#- {icon: "ti-facebook", link: "#"}
#- {icon: "ti-twitter-alt", link: "#"}
#- {icon: "ti-linkedin", link: "#"}
- {icon: "ti-github", link: "https://github.com/courage-max"}

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: courage # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
userID: 4044026246
accessToken: 4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17

#-------------------------------
# Google Analytics
google-analytics: UA-149287662-2 # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 10
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor